// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZqEpjEJaF3Ek43xJ4ynK2c2_IpBxhM-o',
    appId: '1:465925088688:web:2b1c103974542d120ea275',
    messagingSenderId: '465925088688',
    projectId: 'usc-faker',
    authDomain: 'usc-faker.firebaseapp.com',
    storageBucket: 'usc-faker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXoDxAR0p-0O38iXZm8CRcuB9zqXVNwNg',
    appId: '1:465925088688:android:7835b3e6082038d20ea275',
    messagingSenderId: '465925088688',
    projectId: 'usc-faker',
    storageBucket: 'usc-faker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvKbOSd4JBXBaOSOkQ8S_TsZRtrJjJzlc',
    appId: '1:465925088688:ios:54202ff158f90a4c0ea275',
    messagingSenderId: '465925088688',
    projectId: 'usc-faker',
    storageBucket: 'usc-faker.appspot.com',
    iosClientId: '465925088688-4nm6tpvdrd050skrrgh4ff948kgrgm50.apps.googleusercontent.com',
    iosBundleId: 'de.n1c0qn.uscFaker',
  );
}
